import {AbstractJavaAstTransformer, JavaAstTransformerArgs} from '../transform';
import * as Java from '../ast';
import {VisitorFactoryManager} from '@omnigen/core-util';

export class AddGeneratedCommentAstTransformer extends AbstractJavaAstTransformer {

  transformAst(args: JavaAstTransformerArgs): void {

    if (!args.options.includeGenerated) {
      return;
    }

    const defaultVisitor = args.root.createVisitor();
    const unitHasCommentStack: boolean[] = [];

    args.root.visit(VisitorFactoryManager.create(defaultVisitor, {

      visitCompilationUnit: (n, v) => {
        try {
          unitHasCommentStack.push(false);
          return defaultVisitor.visitCompilationUnit(n, v);
        } finally {
          unitHasCommentStack.pop();
        }
      },

      visitObjectDeclaration: node => {

        if (unitHasCommentStack[unitHasCommentStack.length - 1]) {
          return;
        }

        unitHasCommentStack[unitHasCommentStack.length - 1] = true;

        const dateString = new Date().toISOString();
        const commentString = `Generated by Omnigen @ ${dateString}`;

        if (!node.comments) {
          node.comments = new Java.CommentBlock(new Java.FreeText(commentString));
        } else {

          const previousComment = node.comments.text;
          node.comments = new Java.CommentBlock(new Java.FreeTexts(new Java.FreeTextLine(previousComment), new Java.FreeText(commentString)));
        }
      },
    }));
  }
}
