import {AbstractJavaAstTransformer, JavaAstTransformerArgs} from '../transform';
import * as Java from '../ast';
import {VisitorFactoryManager} from '@omnigen/core-util';
import {FreeTextUtils} from '../util/FreeTextUtils.ts';

export class AddGeneratedCommentAstTransformer extends AbstractJavaAstTransformer {

  transformAst(args: JavaAstTransformerArgs): void {

    if (!args.options.includeGenerated) {
      return;
    }

    const defaultVisitor = args.root.createVisitor();
    const unitHasCommentStack: boolean[] = [];

    args.root.visit(VisitorFactoryManager.create(defaultVisitor, {

      visitCompilationUnit: (n, v) => {
        try {
          unitHasCommentStack.push(false);
          return defaultVisitor.visitCompilationUnit(n, v);
        } finally {
          unitHasCommentStack.pop();
        }
      },

      visitObjectDeclaration: node => {

        if (unitHasCommentStack[unitHasCommentStack.length - 1]) {
          return;
        }

        unitHasCommentStack[unitHasCommentStack.length - 1] = true;

        const dateString = new Date().toISOString();
        const commentString = `Generated by Omnigen @ ${dateString}`;

        node.comments = new Java.Comment(FreeTextUtils.add(node.comments?.text, new Java.FreeTextRemark(commentString)), node.comments?.kind);
      },
    }));
  }
}
