namespace generated.omnigen
{
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public class AbortData
  {
    /// <example>9594811343</example>
    public string Orderid { get; }
    /// <summary>
    /// Some descriptive description.
    /// </summary>
    /// <see cref="StringBoolean" />
    public string SystemInitiated { get; }
    /// <see cref="StringBoolean" />
    public string UserInitiated { get; }

    public AbortData(string orderid, string userInitiated, string systemInitiated)
    {
      this.Orderid = orderid;
      this.UserInitiated = userInitiated;
      this.SystemInitiated = systemInitiated;
    }
  }
}