using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace generated.omnigen
{
    /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
    [JsonConverter(typeof(WrapperConverter<Data>), "Raw")]
    public class Data
    {
        private AbortData _abortData;
        private DefaultData _defaultData;

        public Data(JToken raw)
        {
            this.Raw = raw;
        }

        public AbortData GetAbortData(JsonSerializer transformer)
        {
            if (this._abortData != null)
            {
                return this._abortData;
            }
            return this._abortData = this.Raw.ToObject<AbortData>(transformer);
        }

        public DefaultData GetDefaultData(JsonSerializer transformer)
        {
            if (this._defaultData != null)
            {
                return this._defaultData;
            }
            return this._defaultData = this.Raw.ToObject<DefaultData>(transformer);
        }

        public JToken Raw { get; }
    }
}
