using System;

namespace generated.omnigen
{
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public class Data
  {
    private readonly dynamic _raw;
    private AbortData _abortData;
    private DefaultData _defaultData;

    public Data(dynamic raw)
    {
      this._raw = raw;
    }
    
    public AbortData getAbortData(Func<dynamic, AbortData> transformer)
    {
      if (this._abortData != null)
      {
        return this._abortData;
      }
      return this._abortData = transformer(this._raw);
    }

    public DefaultData getDefaultData(Func<dynamic, DefaultData> transformer)
    {
      if (this._defaultData != null)
      {
        return this._defaultData;
      }
      return this._defaultData = transformer(this._raw);
    }

    public dynamic getRaw()
    {
      return this._raw;
    }
  }
}