using System;

namespace generated.omnigen
{
    /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
    public class Data
    {
        private AbortData _abortData;
        private DefaultData _defaultData;

        public Data(dynamic raw)
        {
            this.Raw = raw;
        }

        public AbortData GetAbortData(Func<dynamic, AbortData> transformer)
        {
            if (this._abortData != null)
            {
                return this._abortData;
            }
            return this._abortData = transformer(this.Raw);
        }

        public DefaultData GetDefaultData(Func<dynamic, DefaultData> transformer)
        {
            if (this._defaultData != null)
            {
                return this._defaultData;
            }
            return this._defaultData = transformer(this.Raw);
        }

        public dynamic Raw { get; }
    }
}
