using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace generated.omnigen
{
    /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
    public class DefaultData
    {
        /// <summary>
        /// Some inline description
        /// </summary>
        [JsonProperty("inlineResult")]
        public StringBoolean? InlineResult { get; }
        [JsonProperty("orderid", Required = Required.Always)]
        [Required]
        public string Orderid { get; }

        public DefaultData(string orderid, StringBoolean? inlineResult)
        {
            this.Orderid = orderid;
            this.InlineResult = inlineResult;
        }
    }
}
