namespace generated.omnigen
{
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public static class StringBoolean
  {
    public const string Fail = "0";
    public const string OK = "1";
  }
}
