namespace generated.omnigen
{
  /// <summary>
  /// A comment
  /// </summary>
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public static class Kind1
  {
    public const string _1_A = "1A";
    public const string _1_B = "1B";
  }
}