using System.Runtime.Serialization;

namespace generated.omnigen
{
    /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
    public class AccountNotificationData
    {
        public string Orderid { get; }
        /// <summary>
        /// Whether the account is verified or not. 0 for not verified, 1 for verified.
        /// </summary>
        public StringBoolean? Verified { get; }

        public AccountNotificationData(string orderid, StringBoolean? verified)
        {
            this.Orderid = orderid;
            this.Verified = verified;
        }
    }

    public enum StringBoolean
    {
        [EnumMember(Value = "0")]
        Fail,
        [EnumMember(Value = "1")]
        OK,
    }
}
