namespace generated.omnigen
{
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public class AccountNotificationData
  {
    /// <example>9594811343</example>
    public string Orderid { get; }
    /// <summary>
    /// Whether the account is verified or not. 0 for not verified, 1 for verified.
    /// </summary>
    /// <see cref="StringBoolean" />
    public string Verified { get; }

    public AccountNotificationData(string orderid, string verified)
    {
      this.Orderid = orderid;
      this.Verified = verified;
    }
  }
}