using Newtonsoft.Json.JsonPropertyAttribute;
using Newtonsoft.Json.Required;

namespace generated.omnigen
{
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public class DataEntry
  {
    /// <summary>
    /// The current state of the withdrawal.
    /// </summary>
    /// <example>EXECUTING</example>
    /// <example>EXECUTED</example>
    /// <example>PENDING</example>
    [JsonProperty("transferstate", Required = Required.Always)]
    public string Transferstate { get; }

    public DataEntry(string transferstate)
    {
      this.Transferstate = transferstate;
    }
  }
}
