using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Runtime.Serialization;

namespace generated.omnigen
{
    /// <summary>
    /// Enum Description
    /// </summary>
    /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransferState
    {
        [EnumMember(Value = "EXECUTING")]
        EXECUTING,
        [EnumMember(Value = "EXECUTED")]
        EXECUTED,
        [EnumMember(Value = "PENDING")]
        PENDING,
    }
}
