namespace generated.omnigen
{
  /// <summary>
  /// Enum Description
  /// </summary>
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public static class TransferState
  {
    public const string EXECUTED = "EXECUTED";
    public const string EXECUTING = "EXECUTING";
    public const string PENDING = "PENDING";
  }
}