env:
  browser: true
  es2021: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins: ['@typescript-eslint']

extends:
  - google
  - prettier

rules:
  require-jsdoc: off
  valid-jsdoc: off
  no-trailing-spaces: off
  max-len:
    - warn
    - code: 140

overrides:
  - files: ['*.ts']
    excludedFiles: ['*[Tt]est*']
    extends: ["plugin:@typescript-eslint/recommended", "plugin:@typescript-eslint/recommended-requiring-type-checking"]
    parserOptions:
      project: ['./tsconfig.json']
    rules:
      '@typescript-eslint/explicit-function-return-type': error
