packages:
  - config/*
  - packages/*
  - apps/*
  - tests/*

onlyBuiltDependencies:
  - esbuild

allowBuilds:
  '@swc/core': false
  esbuild: true

catalog:
  typescript: ^7.0.2
  pino-pretty: ^13.1.3
