// Generated by Omnigen @ 2000-01-02T03:04:05.000Z

import { ResponseDataWithReject } from './ResponseDataWithReject.ts';
import { ResponseDataWithResult } from './ResponseDataWithResult.ts';

export type ResponseData = ResponseDataWithReject | ResponseDataWithResult;
