/**
 * Generated by Omnigen @ 2000-01-02T03:04:05.000Z
 */
export interface JsonRpcErrorResponse {
  readonly error: ErrorUnknownError;
  readonly id?: string | undefined;
  readonly jsonrpc?: '2.0' | undefined;
  readonly result?: null | undefined;
}

export interface JsonRpcError {
  readonly code?: number | undefined;
  readonly data?: any | undefined;
  readonly message?: string | undefined;
}

export type ErrorUnknownError = JsonRpcError;
export type ErrorUnknown = JsonRpcErrorResponse;

export interface JsonRpcRequest {
  readonly id?: string | undefined;
  readonly params?: ListThingsRequestParams | undefined;
  jsonrpc: '2.0';
  method: 'list_things';
}

export type JsonRpcRequestParams = object;

export interface Thing {
  readonly id: string;
  readonly [key: string]: any;
}

export type ListThingsRequest = JsonRpcRequest;
export type ListThingsRequestParams = JsonRpcRequestParams;

export interface JsonRpcResponse {
  readonly error?: null | undefined;
  readonly id?: string | undefined;
  readonly jsonrpc?: '2.0' | undefined;
  readonly result?: ReadonlyArray<Thing> | undefined;
}

export type ListThingsResponse = JsonRpcResponse;
