// noinspection JSUnusedGlobalSymbols
// Generated by Omnigen @ 2000-01-02T03:04:05.000Z

export interface AbstractOne extends AbstractOneWithAbstractOnePropertyA {
  readonly AbstractOnePropertyB?: string | undefined;
}

export interface AbstractOther extends AbstractOne {
  readonly AbstractOtherPropertyB: string;
  AbstractOtherPropertyA?: number | undefined;
}

export type ErrorUnknown = JsonRpcErrorResponse;
export type ErrorUnknownError = JsonRpcError;

export interface JsonRpcError {
  /**
   * @default -1
   */
  readonly code?: number | undefined;
  readonly data?: unknown;
  /**
   * @default "Unknown Error"
   */
  readonly message?: string | undefined;
}

export interface JsonRpcErrorResponse {
  readonly error: ErrorUnknownError;
  readonly id?: string | undefined;
  readonly jsonrpc?: '2.0' | undefined;
  readonly result?: null | undefined;
}

export interface JsonRpcRequest {
  readonly id?: string | undefined;
  readonly jsonrpc: '2.0';
  readonly method: 'method';
  readonly params?: MethodRequestParams | undefined;
}

export interface JsonRpcRequestParams {
  readonly RequestParamDescriptor?: RequestParamDescriptor | undefined;
}

export interface JsonRpcResponse {
  readonly error?: null | undefined;
  readonly id?: string | undefined;
  readonly jsonrpc?: '2.0' | undefined;
  readonly result: ResultDescriptor;
}

export type MethodRequest = JsonRpcRequest;
export type MethodRequestParams = JsonRpcRequestParams;
export type MethodResponse = JsonRpcResponse;
export type RequestParamDescriptor = AbstractOther;
export type RequestParamSchema = AbstractOther;

export interface ResultDescriptor extends AbstractOne {
  ResultSchemaPropertyA?: string | undefined;
}

export interface ResultSchema extends AbstractOne {
  ResultSchemaPropertyA?: string | undefined;
}
