/**
 * Generated by Omnigen @ 2000-01-02T03:04:05.000Z
 */
export interface AbstractRequestData {
  readonly Password: string;
  readonly Username: string;
  readonly [key: string]: unknown;
}

export interface AbstractResponseResult<TData, TMethod extends string> {
  readonly data: TData;
  readonly method: TMethod;
  readonly signature: string;
  readonly uuid: string;
}

export type DepositRequest = JsonRpcRequest<DepositRequestParams, 'Deposit'>;

export interface DepositRequestData extends AbstractRequestData {
  readonly NotificationURL: string;
}

export type DepositRequestParams = JsonRpcRequestParams<DepositRequestData>;
export type DepositResponse = JsonRpcResponse<DepositResponseResult>;

export interface DepositResponseData {
  readonly orderid?: string | undefined;
  readonly url?: string | undefined;
}

export type DepositResponseResult = AbstractResponseResult<DepositResponseData, 'Deposit'>;
export type ErrorUnknown = JsonRpcErrorResponse;
export type ErrorUnknownError = JsonRpcError;

export interface JsonRpcError {
  /**
   * @default -1
   */
  readonly code?: number | undefined;
  readonly data?: unknown;
  /**
   * @default "Unknown Error"
   */
  readonly message?: string | undefined;
}

export interface JsonRpcErrorResponse {
  readonly error: ErrorUnknownError;
  readonly id?: string | undefined;
  readonly jsonrpc?: '2.0' | undefined;
  readonly result?: null | undefined;
}

export interface JsonRpcRequest<TParams extends JsonRpcRequestParams<AbstractRequestData>, TMethod extends string> {
  readonly id?: string | undefined;
  readonly jsonrpc: '2.0';
  readonly method: TMethod;
  readonly params?: TParams | undefined;
}

export interface JsonRpcRequestParams<T extends AbstractRequestData> {
  readonly Data: T;
  readonly UUID: string;
}

export interface JsonRpcResponse<T extends AbstractResponseResult<unknown, string>> {
  readonly error?: null | undefined;
  readonly id?: string | undefined;
  readonly jsonrpc?: '2.0' | undefined;
  readonly result: T;
}

export type RefundRequest = JsonRpcRequest<RefundRequestParams, 'Refund'>;

export interface RefundRequestData extends AbstractRequestData {
  readonly Amount: string;
  readonly OrderID: string;
}

export type RefundRequestParams = JsonRpcRequestParams<RefundRequestData>;
export type RefundResponse = JsonRpcResponse<RefundResponseResult>;

export interface RefundResponseData {
  readonly orderid: string;
  readonly result: string;
}

export type RefundResponseResult = AbstractResponseResult<RefundResponseData, 'Refund'>;
