/**
 * Generated by Omnigen @ 2000-01-02T03:04:05.000Z
 */
export interface A extends Abs {
  readonly foo?: string | undefined;
}

export interface Abs {
  readonly kind?: string | undefined;
}

export interface B extends Abs {
  readonly bar?: string | undefined;
}

export interface C extends Abs {
  readonly xyz?: string | undefined;
}

export type ErrorUnknown = JsonRpcErrorResponse;
export type ErrorUnknownError = JsonRpcError;
export type GiveInGetOut2Request = JsonRpcRequest<GiveInGetOut2RequestParams, 'give_in_get_out2'>;
export type GiveInGetOut2RequestParams = JsonRpcRequestParams;
export type GiveInGetOut2Response = JsonRpcResponse<Out2>;
export type GiveInGetOutRequest = JsonRpcRequest<GiveInGetOutRequestParams, 'give_in_get_out'>;
export type GiveInGetOutRequestParams = JsonRpcRequestParams;
export type GiveInGetOutResponse = JsonRpcResponse<Out>;
export type In = InInterface & (A | B);

export interface InInterface {
  readonly in_type?: string | undefined;
}

export interface JsonRpcError {
  /**
   * @default -1
   */
  readonly code?: number | undefined;
  readonly data?: unknown;
  /**
   * @default "Unknown Error"
   */
  readonly message?: string | undefined;
}

export interface JsonRpcErrorResponse {
  readonly error: ErrorUnknownError;
  readonly id?: string | undefined;
  readonly jsonrpc?: '2.0' | undefined;
  readonly result?: null | undefined;
}

export interface JsonRpcRequest<TParams extends JsonRpcRequestParams, TMethod extends string> {
  readonly id?: string | undefined;
  readonly jsonrpc: '2.0';
  readonly method: TMethod;
  readonly params?: TParams | undefined;
}

export interface JsonRpcRequestParams {
  readonly param?: In | undefined;
}

export interface JsonRpcResponse<T> {
  readonly error?: null | undefined;
  readonly id?: string | undefined;
  readonly jsonrpc?: '2.0' | undefined;
  readonly result?: T | undefined;
}

export interface Out {
  readonly result?: string | undefined;
}

export interface Out2 extends B, C, A {

}
