using Newtonsoft.Json;

namespace generated.omnigen
{
    /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
    public class RequestData
    {
        [JsonProperty("senderInformation")]
        public SenderInformation SenderInformation { get; }

        public RequestData(SenderInformation senderInformation)
        {
            this.SenderInformation = senderInformation;
        }
    }

    public class SenderInformation
    {
        /// <summary>
        /// A description
        /// </summary>
        /// <remarks>Date string in the ISO 8601 format (YYYY-MM-DD), An organization number</remarks>
        /// <example>2014-04-01</example>
        [JsonProperty("DateOfBirth")]
        public string DateOfBirth { get; }

        public SenderInformation(string dateOfBirth)
        {
            this.DateOfBirth = dateOfBirth;
        }
    }
}
