namespace generated.omnigen
{
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public class RequestData
  {
    public SenderInformation SenderInformation { get; }

    public RequestData(SenderInformation senderInformation)
    {
      this.SenderInformation = senderInformation;
    }
  }
  public class SenderInformation
  {
    /// <summary>
    /// Date string in the ISO 8601 format (YYYY-MM-DD), A description, An organization number
    /// </summary>
    /// <example>2014-04-01</example>
    public string DateOfBirth { get; }

    public SenderInformation(string dateOfBirth)
    {
      this.DateOfBirth = dateOfBirth;
    }
  }
}