import {IAstVisitor, IAstNode, VisitFn} from '@omnigen/core';
import * as Java from '../ast';

export type JavaVisitFn<in N extends IAstNode, R> = VisitFn<N, R, IJavaAstVisitor<R>>;

export interface IJavaAstVisitor<R> extends IAstVisitor<R> {
  visitor_java: IJavaAstVisitor<R>;
  visitRegularType: JavaVisitFn<Java.RegularType, R>;
  visitGenericType: JavaVisitFn<Java.GenericType, R>;
  visitIdentifier: JavaVisitFn<Java.Identifier, R>;
  visitToken: JavaVisitFn<Java.JavaToken, R>;
  visitAnnotationList: JavaVisitFn<Java.AnnotationList, R>;
  visitArgumentDeclaration: JavaVisitFn<Java.ArgumentDeclaration, R>;
  visitArgumentDeclarationList: JavaVisitFn<Java.ArgumentDeclarationList, R>;
  visitBinaryExpression: JavaVisitFn<Java.BinaryExpression, R>;
  visitModifier: JavaVisitFn<Java.Modifier, R>;
  visitField: JavaVisitFn<Java.Field, R>;
  visitCommentList: JavaVisitFn<Java.CommentList, R>;
  visitComment: JavaVisitFn<Java.Comment, R>;
  visitFieldBackedGetter: JavaVisitFn<Java.FieldBackedGetter, R>;
  visitFieldBackedSetter: JavaVisitFn<Java.FieldBackedSetter, R>;
  visitMethodDeclaration: JavaVisitFn<Java.MethodDeclaration, R>;
  visitAbstractMethodDeclaration: JavaVisitFn<Java.AbstractMethodDeclaration, R>;
  visitMethodDeclarationSignature: JavaVisitFn<Java.MethodDeclarationSignature, R>;
  visitExtendsDeclaration: JavaVisitFn<Java.ExtendsDeclaration, R>;
  visitImplementsDeclaration: JavaVisitFn<Java.ImplementsDeclaration, R>;
  visitTypeList: JavaVisitFn<Java.TypeList, R>;
  visitLiteral: JavaVisitFn<Java.Literal, R>;
  visitIfStatement: JavaVisitFn<Java.IfStatement, R>;
  visitIfElseStatement: JavaVisitFn<Java.IfElseStatement, R>;
  visitImportStatement: JavaVisitFn<Java.ImportStatement, R>;
  visitImportList: JavaVisitFn<Java.ImportList, R>;
  visitMethodCall: JavaVisitFn<Java.MethodCall, R>;
  visitNewStatement: JavaVisitFn<Java.NewStatement, R>;
  visitArgumentList: JavaVisitFn<Java.ArgumentList, R>;
  visitReturnStatement: JavaVisitFn<Java.ReturnStatement, R>;
  visitVariableDeclaration: JavaVisitFn<Java.VariableDeclaration, R>;
  visitVariableReference: JavaVisitFn<Java.VariableReference, R>;
  visitAnnotation: JavaVisitFn<Java.Annotation, R>;
  visitAnnotationKeyValuePairList: JavaVisitFn<Java.AnnotationKeyValuePairList, R>;
  visitAnnotationKeyValuePair: JavaVisitFn<Java.AnnotationKeyValuePair, R>;
  visitHardCoded: JavaVisitFn<Java.HardCoded, R>;
  visitBlock: JavaVisitFn<Java.Block, R>;
  visitPackage: JavaVisitFn<Java.PackageDeclaration, R>;
  visitPredicate: JavaVisitFn<Java.Predicate, R>;
  visitModifierList: JavaVisitFn<Java.ModifierList, R>;
  visitFieldGetterSetter: JavaVisitFn<Java.FieldGetterSetter, R>;
  visitCast: JavaVisitFn<Java.Cast, R>;
  visitObjectDeclaration: JavaVisitFn<Java.AbstractObjectDeclaration, R>;
  visitClassDeclaration: JavaVisitFn<Java.ClassDeclaration, R>;
  visitInterfaceDeclaration: JavaVisitFn<Java.InterfaceDeclaration, R>;
  visitEnumDeclaration: JavaVisitFn<Java.EnumDeclaration, R>;
  visitEnumItem: JavaVisitFn<Java.EnumItem, R>;
  visitEnumItemList: JavaVisitFn<Java.EnumItemList, R>;
  visitFieldReference: JavaVisitFn<Java.FieldReference, R>;
  visitAssignExpression: JavaVisitFn<Java.AssignExpression, R>;
  visitCompilationUnit: JavaVisitFn<Java.CompilationUnit, R>;
  visitConstructor: JavaVisitFn<Java.ConstructorDeclaration, R>;
  visitAdditionalPropertiesDeclaration: JavaVisitFn<Java.AdditionalPropertiesDeclaration, R>;
  visitStatement: JavaVisitFn<Java.Statement, R>;
  visitSuperConstructorCall: JavaVisitFn<Java.SuperConstructorCall, R>;
  visitRuntimeTypeMapping: JavaVisitFn<Java.RuntimeTypeMapping, R>;
  visitClassName: JavaVisitFn<Java.ClassName, R>;
  visitClassReference: JavaVisitFn<Java.ClassReference, R>;
  visitGenericClassDeclaration:  JavaVisitFn<Java.GenericClassDeclaration, R>;
  visitGenericTypeDeclarationList:  JavaVisitFn<Java.GenericTypeDeclarationList, R>;
  visitGenericTypeDeclaration:  JavaVisitFn<Java.GenericTypeDeclaration, R>;
  visitGenericTypeUse:  JavaVisitFn<Java.GenericTypeUse, R>;
  visitGenericTypeUseList:  JavaVisitFn<Java.GenericTypeUseList, R>;
  visitArrayInitializer:  JavaVisitFn<Java.ArrayInitializer<Java.AbstractJavaNode>, R>;
  visitStaticMemberReference: JavaVisitFn<Java.StaticMemberReference, R>;
  visitSelfReference: JavaVisitFn<Java.SelfReference, R>;
}
