namespace generated.omnigen
{
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public class AbstractRequestData
  {
    public string Password { get; }
    public string Username { get; }

    public AbstractRequestData(string username, string password)
    {
      this.Username = username;
      this.Password = password;
    }
  }
}
