namespace generated.omnigen
{
    /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
    public class BalanceRequestData : AbstractRequestData
    {
        public BalanceRequestData(string username, string password) : base(username, password) { }
    }
}
