namespace generated.omnigen
{
    /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
    public class CancelChargeRequestData : AbstractRequestData, ICancelChargeRequestDataBase
    {
        public double OrderID { get; }

        public CancelChargeRequestData(string username, string password, double orderId) : base(username, password)
        {
            this.OrderID = orderId;
        }
    }
}
