using Newtonsoft.Json.JsonPropertyAttribute;

namespace generated.omnigen
{
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public class Container
  {
    /// <summary>
    /// Date string in the ISO 8601 format (YYYY-MM-DD), Date of birth (YYYY-MM-DD, ISO 8601) of the beneficiary, or organisational number for the organisation.
    /// </summary>
    /// <example>2014-04-01</example>
    [JsonProperty("dateOfBirth")]
    public string DateOfBirth { get; }

    public Container(string dateOfBirth)
    {
      this.DateOfBirth = dateOfBirth;
    }
  }
}
