using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace generated.omnigen
{
    /// <summary>
    /// Description about the Shop
    /// </summary>
    /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
    public class Shop
    {
        /// <summary>
        /// Unique Shop Id
        /// </summary>
        [JsonProperty("id", Required = Required.Always)]
        [Required]
        public int Id { get; }
        [JsonProperty("name", Required = Required.Always)]
        [Required]
        public string Name { get; }
        /// <summary>
        /// List of orders currently in this shop
        /// </summary>
        [JsonProperty("orders")]
        public IList<Order> Orders { get; }
        [JsonProperty("tag")]
        public string Tag { get; }

        public Shop(int id, IList<Order> orders, string name, string tag)
        {
            this.Id = id;
            this.Orders = orders;
            this.Name = name;
            this.Tag = tag;
        }
    }
}
