namespace generated.omnigen
{
  /// <summary>
  /// Description about the Shop
  /// </summary>
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public class Shop
  {
    /// <summary>
    /// Unique Shop Id
    /// </summary>
    public int Id { get; }
    public string Name { get; }
    /// <summary>
    /// List of orders currently in this shop
    /// </summary>
    public Order[] Orders { get; }
    public string Tag { get; }

    public Shop(int id, Order[] orders, string name, string tag)
    {
      this.Id = id;
      this.Orders = orders;
      this.Name = name;
      this.Tag = tag;
    }
  }
}