import {Visitor} from '@omnigen/core';
import {AstTransformer, AstTransformerArguments, TargetOptions} from '@omnigen/api';
import {CodeRootAstNode} from '../CodeRootAstNode.ts';
import * as Code from '../CodeAst';
import * as FreeText from '../FreeText';
import {CodeOptions} from '../../options/CodeOptions.ts';
import {FreeTextUtils} from '../../util/FreeTextUtils.ts';

export class AddGeneratedCommentAstTransformer implements AstTransformer<CodeRootAstNode, TargetOptions & CodeOptions> {

  transformAst(args: AstTransformerArguments<CodeRootAstNode, TargetOptions & CodeOptions>): void {

    if (!args.options.includeGenerated) {
      return;
    }

    const defaultVisitor = args.root.createVisitor();
    const unitHasCommentStack: boolean[] = [];

    args.root.visit(Visitor.create(defaultVisitor, {

      visitCompilationUnit: (n, v) => {
        try {
          unitHasCommentStack.push(false);
          return defaultVisitor.visitCompilationUnit(n, v);
        } finally {
          unitHasCommentStack.pop();
        }
      },

      visitObjectDeclaration: node => {

        if (unitHasCommentStack[unitHasCommentStack.length - 1]) {
          return;
        }

        unitHasCommentStack[unitHasCommentStack.length - 1] = true;

        const dateString = new Date().toISOString();
        const commentString = `Generated by Omnigen @ ${dateString}`;

        node.comments = new Code.Comment(FreeTextUtils.add(node.comments?.text, new FreeText.FreeTextRemark(commentString)), node.comments?.kind);
      },
    }));
  }
}
