using Newtonsoft.Json;

namespace generated.omnigen
{
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public class ResponseData
  {
    private ResponseDataWithReject _responseDataWithReject;
    private ResponseDataWithResult _responseDataWithResult;

    public ResponseData(dynamic raw)
    {
      this.Raw = raw;
    }

    public ResponseDataWithReject getResponseDataWithReject(Func<dynamic, ResponseDataWithReject> transformer)
    {
      if (this._responseDataWithReject != null)
      {
        return this._responseDataWithReject;
      }
      return this._responseDataWithReject = transformer(this.Raw);
    }

    public ResponseDataWithResult getResponseDataWithResult(Func<dynamic, ResponseDataWithResult> transformer)
    {
      if (this._responseDataWithResult != null)
      {
        return this._responseDataWithResult;
      }
      return this._responseDataWithResult = transformer(this.Raw);
    }

    public dynamic Raw { get; }
  }
  public class ResponseDataWithReject
  {
    [JsonProperty("rejected", Required = Required.Always)]
    public string Rejected { get; }
    [JsonProperty("result")]
    public string Result { get; } = "0";

    public ResponseDataWithReject(string rejected)
    {
      this.Rejected = rejected;
    }
  }
  public class ResponseDataWithResult
  {
    [JsonProperty("result")]
    public string Result { get; } = "1";
  }
}
