namespace generated.omnigen
{
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public class ResponseData
  {
    private readonly dynamic _raw;
    private ResponseDataWithReject _responseDataWithReject;
    private ResponseDataWithResult _responseDataWithResult;

    public ResponseData(dynamic raw)
    {
      this._raw = raw;
    }
    
    public dynamic getRaw()
    {
      return this._raw;
    }

    public ResponseDataWithReject getResponseDataWithReject(Func<dynamic, ResponseDataWithReject> transformer)
    {
      if (this._responseDataWithReject != null)
      {
        return this._responseDataWithReject;
      }
      return this._responseDataWithReject = transformer(this._raw);
    }

    public ResponseDataWithResult getResponseDataWithResult(Func<dynamic, ResponseDataWithResult> transformer)
    {
      if (this._responseDataWithResult != null)
      {
        return this._responseDataWithResult;
      }
      return this._responseDataWithResult = transformer(this._raw);
    }
  }
  public class ResponseDataWithReject
  {
    public string Rejected { get; }
    public string Result { get; } = "0";

    public ResponseDataWithReject(string rejected)
    {
      this.Rejected = rejected;
    }
  }
  public class ResponseDataWithResult
  {
    public string Result { get; } = "1";
  }
}
