namespace generated.omnigen
{
  /// <summary>
  /// Generic class to describe the JsonRpc request package
  /// </summary>
  /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
  public abstract class JsonRpcRequest
  {
    public JsonRpcRequest(string id)
    {
      this.Id = id;
    }

    public abstract string Method { get; }
    public string Id { get; }
    public string Jsonrpc { get; } = "2.0";
  }
  public class GiveIn1GetOut1Request : JsonRpcRequest
  {
    public GiveIn1GetOut1RequestParams @params { get; }
    public string Method { get; } = "give_in1_get_out1";

    public GiveIn1GetOut1Request(string id, GiveIn1GetOut1RequestParams @params) : base(id)
    {
      this.@params = @params;
    }
  }
  public class GiveIn1GetOut1RequestParams : JsonRpcRequestParams
  {
    public In1 Param { get; }

    public GiveIn1GetOut1RequestParams(In1 param)
    {
      this.Param = param;
    }
  }
  /// <summary>
  /// Generic class to describe the JsonRpc response package
  /// </summary>
  public class JsonRpcResponse
  {
    public string Id { get; }
    public string Jsonrpc { get; } = "2.0";

    public JsonRpcResponse(string id)
    {
      this.Id = id;
    }
  }
  public class GiveIn1GetOut1Response : JsonRpcResponse
  {
    public A Result { get; }

    public GiveIn1GetOut1Response(string id, A result) : base(id)
    {
      this.Result = result;
    }
  }
  public class A : Abs
  {
    public string A { get; }
    public string X { get; }

    public A(string kind, string common, string a, string x) : base(kind, common)
    {
      this.A = a;
      this.X = x;
    }
  }
  /// <summary>
  /// Generic class to describe the JsonRpc error response package
  /// </summary>
  public class JsonRpcErrorResponse
  {
    public ErrorUnknownError Error { get; }
    public string Id { get; }
    public string Jsonrpc { get; } = "2.0";

    public JsonRpcErrorResponse(ErrorUnknownError error, string id)
    {
      this.Error = error;
      this.Id = id;
    }
  }
  public class ErrorUnknown : JsonRpcErrorResponse
  {
    public ErrorUnknown(ErrorUnknownError error, string id) : base(error, id)
    {

    }
  }
  public class GiveIn2GetOut2Request : JsonRpcRequest
  {
    public GiveIn2GetOut2RequestParams @params { get; }
    public string Method { get; } = "give_in2_get_out2";

    public GiveIn2GetOut2Request(string id, GiveIn2GetOut2RequestParams @params) : base(id)
    {
      this.@params = @params;
    }
  }
  public class GiveIn2GetOut2RequestParams : JsonRpcRequestParams
  {
    public In2 Param { get; }

    public GiveIn2GetOut2RequestParams(In2 param)
    {
      this.Param = param;
    }
  }
  public class GiveIn2GetOut2Response : JsonRpcResponse
  {
    public B Result { get; }

    public GiveIn2GetOut2Response(string id, B result) : base(id)
    {
      this.Result = result;
    }
  }
  public class B : Abs
  {
    public string B { get; }
    public double X { get; }

    public B(string kind, string common, string b, double x) : base(kind, common)
    {
      this.B = b;
      this.X = x;
    }
  }
  /// <summary>
  /// Generic class to describe the JsonRpc request params
  /// </summary>
  public class JsonRpcRequestParams
  {

  }
  public class In1
  {
    public string Value { get; }

    public In1(string value)
    {
      this.Value = value;
    }
  }
  public class Abs
  {
    public string Common { get; }
    public string Kind { get; }

    public Abs(string kind, string common)
    {
      this.Kind = kind;
      this.Common = common;
    }
  }
  public class In2
  {
    public string Value { get; }

    public In2(string value)
    {
      this.Value = value;
    }
  }
  /// <summary>
  /// Generic class to describe the JsonRpc error inside an error response
  /// </summary>
  public class JsonRpcError
  {
    public int? Code { get; }
    public dynamic Data { get; }
    public string Message { get; }

    public JsonRpcError(int? code, string message, dynamic data)
    {
      this.Code = ((code == null) ? -1 : code);
      this.Message = ((message == null) ? "Unknown Error" : message);
      this.Data = data;
    }
  }
  public class ErrorUnknownError : JsonRpcError
  {
    public ErrorUnknownError(int? code, string message, dynamic data) : base(((code == null) ? -1 : code), ((message == null) ? "Unknown Error" : message), ((object) data))
    {

    }
  }
}
