namespace generated.omnigen
{
    /// <remarks>Generated by Omnigen @ 2000-01-02T03:04:05.000Z</remarks>
    public enum SomeEnum
    {
        Zero = 0,
        One = 1,
        Two = 2,
        Three = 3,
    }
}
